spring:
  application:
    name: feignaut
  cloud:
    refresh:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dest
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id : test-dest
            client-secret : g1QNqxOLLG7rz0UJAtQEBJpbSknLQejN
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/dest
            tokenUri: http://localhost:8080/realms/dest/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/dest/protocol/openid-connect/auth
server:
  port: 8067
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true