spring:
  application:
    name: feignaut
  cloud:
    refresh:
      enabled: true
#    compatibility-verifier:
#      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dest
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id : test-dest
            client-secret : JQ37LPXbUcXyT6Fpsw2EwTdgMORF6zC4
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/dest
            tokenUri: http://localhost:8080/realms/dest/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/dest/protocol/openid-connect/auth
server:
  port: 8067
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

logging:
  level:
    web: DEBUG
    com.titov: DEBUG
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
